---
title: "Initial Web Mining"
author: "Jinfei Xue"
date: "Nov 16, 2018"
output:
  html_document:
    df_print: paged
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
#install.packages("rvest")
#install.packages("dplyr")
#install.packages("knitr")
#install.packages("tm")
#install.packages("rJava")
#install.packages("tm.plugin.webmining")
library(rvest)
library(dplyr)
library(knitr)
library(tm)
library(rJava)
library(tm.plugin.webmining)
```

## War Timeline

```{r, warning=FALSE, message=FALSE}

url <- "https://www.iwm.org.uk/history/timeline-of-20th-and-21st-century-wars"
timeline <- url %>%
    read_html() %>%
    html_nodes(css = 'strong')%>%
  html_text() 

timeline <- timeline[!timeline %in% c("?C", "?C19", "?C199")]

war <- rep(NA, length(timeline))
time <- rep(NA, length(timeline))
for (i in 1:length(timeline)) {
  war[i] <- unlist(strsplit(timeline[i], ", "))[1]
  time[i] <- unlist(strsplit(timeline[i], ", "))[2]
}
war_tl <- unique(data.frame(war, time))
rownames(war_tl) <- 1:19
kable(war_tl)

```

## Common Factors Research

We first search for some researches about common factors of wars.

### The 8 Main Reasons for War
```{r}
url <- "https://owlcation.com/social-sciences/The-Main-Reasons-For-War"
# 8 Main Reasons
MRW <- url %>%
    read_html() %>%
    html_nodes(xpath = '//*[@id="txtd_45775170"]')%>%
  html_text() 
MRW <- unlist(strsplit(MRW, "\n"))
MRW <- MRW[-9]
# War examples for each main reason
war_ex <- url %>%
    read_html() %>%
    html_nodes(css = 'li strong')%>%
  html_text() 
war_ex <- war_ex[1:23]
# Combine
reasons <- rep(MRW, c(2,3,5,2,2,4,4,1))
mrw <- data.frame(reasons, war_ex)
kable(mrw)

```

We can see the eight main reasons for wars are "Economic Gain", "Territorial Gain", "Religion", "Nationalism", "Revenge", "Civil War", "Revolutionary War" and "Defensive War".

### The Causes of War and Those of Peace
```{r}
url <- "https://www.theobjectivestandard.com/2014/10/causes-war-peace/"
# Wikipedia: Causes of Wars
causes <- url %>%
    read_html() %>%
    html_nodes(css = 'td:nth-child(1) strong')%>%
  html_text() 
causes

```

## the First World War 
```{r}
# The Origins of WWI
url_1 <- "https://www.historyonthenet.com/authentichistory/1914-1920/1-overview/1-origins/index.html"
ww1_1 <- url %>%
    read_html() %>%
    html_nodes(css = 'strong , .body_text .header')%>%
  html_text() 
ww1_1

# 
url_2 <- "https://www.historyonthenet.com/authentichistory/1914-1920/1-overview/1-origins/index.html"
ww1_2 <- url %>%
    read_html() %>%
    html_nodes(css = 'strong , .body_text .header')%>%
  html_text() 
ww1_2

```

## the Second World War 
```{r}
# The Origins of WWI
url_1 <- "https://www.historyonthenet.com/authentichistory/1914-1920/1-overview/1-origins/index.html"
ww1_1 <- url %>%
    read_html() %>%
    html_nodes(css = 'strong , .body_text .header')%>%
  html_text() 
ww1_1

# 
url_2 <- "https://www.historyonthenet.com/authentichistory/1914-1920/1-overview/1-origins/index.html"
ww1_2 <- url %>%
    read_html() %>%
    html_nodes(css = 'strong , .body_text .header')%>%
  html_text() 
ww1_2

```

# 
```{r}


```




